// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omodpymgfwvoduzkfakj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tb2RweW1nZnd2b2R1emtmYWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDI2MzAsImV4cCI6MjA2NzM3ODYzMH0.c5tZMJwdY5vg0P-eT0dP7IfxsIJ39YyQCcTWs4HPftY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});